// Minimal zero-dependency PDF writer for a one-page appointment confirmation. Produces a valid
// PDF 1.4 buffer using the built-in Helvetica fonts (no npm dependency).

const esc = (s) => String(s ?? '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');

export function appointmentPdf({ hospital = 'Medinity Hospital', address = '', patient, doctor, department, slot, ticketNo, generatedAt = '' }) {
  const ops = [];
  const text = (x, y, size, font, s) => ops.push(`BT /${font} ${size} Tf ${x} ${y} Td (${esc(s)}) Tj ET`);
  const rule = (y) => ops.push(`0.7 w 60 ${y} m 535 ${y} l S`);

  text(60, 792, 22, 'F1', hospital);
  if (address) text(60, 772, 10, 'F2', address);
  rule(760);
  text(60, 722, 16, 'F1', 'Appointment Confirmation');
  text(60, 700, 11, 'F2', `Reference: ${ticketNo || '-'}`);

  const kv = [
    ['Patient', patient],
    ['Department', department],
    ['Doctor', doctor],
    ['Date & time', slot],
    ['Status', 'Confirmed'],
  ];
  let y = 662;
  for (const [k, v] of kv) {
    text(60, y, 11, 'F1', `${k}:`);
    text(190, y, 11, 'F2', v || '-');
    y -= 26;
  }
  rule(y);
  text(60, y - 26, 9, 'F2', 'Please arrive 15 minutes early and carry a valid ID.');
  text(60, y - 42, 9, 'F2', 'To reschedule or cancel, reply to this WhatsApp chat.');
  text(60, 60, 8, 'F2', `${hospital} · Generated by Medinity Connect${generatedAt ? ' · ' + generatedAt : ''}`);

  const content = ops.join('\n');
  const len = Buffer.byteLength(content, 'latin1');
  const objs = [
    '<</Type/Catalog/Pages 2 0 R>>',
    '<</Type/Pages/Kids[3 0 R]/Count 1>>',
    '<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 4 0 R/F2 5 0 R>>>>/Contents 6 0 R>>',
    '<</Type/Font/Subtype/Type1/BaseFont/Helvetica-Bold>>',
    '<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>',
    `<</Length ${len}>>\nstream\n${content}\nendstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [];
  objs.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((o) => (pdf += String(o).padStart(10, '0') + ' 00000 n \n'));
  pdf += `trailer\n<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, 'latin1');
}
